department_topics:
  department-of-finance:
    blurb: >
      The Budget, financial reporting processes, asset management and more.
    topics:
      - name: Budget
        image: related_topics/budget.png
      - name: Government advertising
        image: related_topics/government_advertising.png
      - name: Parliamentary entitlements
        image: related_topics/parliamentary_entitlements.png
  department-of-health:
    blurb: Health conditions, solutions, insurance and more.
    topics:
      - name: Ageing and aged care
        image: related_topics/ageing.png
      - name: Health emergencies
        image: related_topics/health_emergencies.png
      - name: My Health Record
        image: related_topics/health_record.png
  department-of-immigration-and-border-protection:
    blurb: Visiting, working and studying in Australia and more.
    topics:
      - name: Citizenship
        image: related_topics/citizenship.png
      - name: Visas
        image: related_topics/visas.png
      - name: Visiting Australia
        image: related_topics/visiting_australia.png
  department-of-the-prime-minister-and-cabinet:
    blurb: Security, public data, climate change and more.
    topics:
      - name: Cyber Security
        image: related_topics/cyber_security.png
      - name: National Security
        image: related_topics/national_security.png
      - name: Climate change
        image: related_topics/climate_change.png
  department-of-communications-and-the-arts:
    blurb: The internet, television, phones, the arts and more.
    topics:
      - name: Television reception
        image: related_topics/television_reception.png
        url: /television-tv-reception
      - name: Online safety
        image: related_topics/online_safety.png
      - name: Arts
        image: related_topics/arts.png
