categories:
  - name: Business and industry
    summary: >
      ABNs, grants, non-profit and small business, primary industry, import and
      export, tenders.
  - name: Crime, justice and the law
    summary: >
      Consumer protection, fraud, online safety, scams, emergency services,
      legislation, police, rights.
  - name: Culture, sport and the arts
    summary: >
      Indigenous heritage and history, arts grants, cultural institutions,
      honours and awards, family history.
  - name: Education
    summary: >
      Early childhood, school, higher education, international students,
      skills recognition, scholarships, VET.
  - name: Emergencies and disasters
    summary: >
      Triple Zero (000), natural disasters, search and rescue, disaster
      assistance, health emergencies.
  - name: Environment and agriculture
    summary: >
      Energy efficiency, environmental management and protection, biodiversity,
      grants, natural resources.
  - name: Health and family
    summary: >
      Workplace health and safety, drug and alcohol use, health insurance,
      children's health, mental health, sport.
  - name: Immigration, visas and citizenship
    summary: >
      Australian citizenship, customs, work, study and short-term visas,
      migration and tourism.
  - name: Infrastructure and telecommunications
    summary: >
      Regional development, transport safety, Television (TV) reception,
      internet, telecommunications.
    path: /categories/infrastructure-and-telecommunications
  - name: Jobs and work
    summary: >
      Careers, government jobs, employment services, disability employment,
      working conditions.
  - name: Money, tax and super
    summary: >
      Tax returns, ABNs, superannuation, personal finance, financial regulation.
  - name: Science
    summary: >
      Science grants and awards, Chief Scientist, National Measurement
      Institute, radioactive waste, space.
  - name: Security and defence
    summary: >
      National security, cyber security, ADF, military history, commemoration.
  - name: Trade and international
    summary: >
      Importing, exporting, free trade agreements, wildlife trade, economic
      diplomacy, foreign investment, foreign aid.
  - name: Travelling overseas
    summary: >
      Customs and quarantine, embassies and consulates, travelling overseas.
  - name: About Australia
    summary: >
      Intergenerational report, currency, National archives collection,
      Australian honours, the constitution.
  - name: About Government
    summary: >
      Government structure, freedom of information, elections and voting,
      Budget, Australian Public Service.
department_topics:
  department-of-finance:
    blurb: >
      The Budget, financial reporting processes, asset management and more.
    topics:
      - name: Budget
        image: related_topics/budget.png
      - name: Government advertising
        image: related_topics/government_advertising.png
      - name: Parliamentary entitlements
        image: related_topics/parliamentary_entitlements.png
  department-of-health:
    blurb: Health conditions, solutions, insurance and more.
    topics:
      - name: Ageing and aged care
        image: related_topics/ageing.png
      - name: Health emergencies
        image: related_topics/health_emergencies.png
      - name: My Health Record
        image: related_topics/health_record.png
  department-of-immigration-and-border-protection:
    blurb: Visiting, working and studying in Australia and more.
    topics:
      - name: Citizenship
        image: related_topics/citizenship.png
      - name: Visas
        image: related_topics/visas.png
      - name: Visiting Australia
        image: related_topics/visiting_australia.png
  department-of-the-prime-minister-and-cabinet:
    blurb: Security, public data, climate change and more.
    topics:
      - name: Cyber Security
        image: related_topics/cyber_security.png
      - name: National Security
        image: related_topics/national_security.png
      - name: Climate change
        image: related_topics/climate_change.png
  department-of-communications-and-the-arts:
    blurb: The internet, television, phones, the arts and more.
    topics:
      - name: Television reception
        image: related_topics/television_reception.png
        url: /television-tv-reception
      - name: Online safety
        image: related_topics/online_safety.png
      - name: Arts
        image: related_topics/arts.png
