source 'https://rubygems.org'

# Declare your gem's dependencies in synergy.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]


group :test, :development do
  gem 'rspec-rails', '>= 3.5.0.beta3'
  gem 'fabrication', '~> 2.15.0'
  gem 'sqlite3'
  gem 'pry'
end
